name: cr_calendar
description: Awesome calendar with customizations, range picking and event showing.
version: 0.0.10
homepage: https://cleveroad.com
repository: https://github.com/Cleveroad/cr_calendar

environment:
  sdk: '>=2.12.2 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  jiffy: ^5.0.0
  scrollable_positioned_list: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

