name: cr_calendar
description: Awesome calendar with customizations, range picking and event showing.
version: 0.0.3
homepage: https://cleveroad.com
repository: https://github.com/Cleveroad/CRCalendar

environment:
  sdk: '>=2.12.2 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  jiffy: ^4.1.0
  scrollable_positioned_list: ^0.2.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

