name: cr_calendar
description: Awesome calendar with customizations, range picking and event showing.
version: 1.1.0
homepage: https://cleveroad.com
repository: https://github.com/Cleveroad/cr_calendar

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  jiffy: ^6.1.0
  scrollable_positioned_list: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

